title: Alex Dreyzin # your name (or website title) here
logo: "images/Alex Dreyzin - square - Copy.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Business Data Analyst | SQL | Power BI | Python
  <br><br>
    Data Analyst with over 25 years of expertise in financial services, business intelligence, data integration, and process improvement. Skilled in identifying patterns and trends to support strategic decision-making and operational efficiency.
  <br><br>
  <a href="https://www.linkedin.com/in/alexdreyzin/">View My LinkedIn Profile</a> 
  <br><br>
  theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
